main: dk.thorvaldemar.Main
version: 1.0
name: CityDefender

commands:
  bct:
    description: broadcast title
  selector:
    description: manipulating selectors
  pc:
    description: main commands
  protectcity:
    description: main commands